"""
Django settings for academia_project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b8%#e5se7tyx%3$+ws++zbwi)p$4+aq8-e@)21nf*9k^7qk#$r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'simulador',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'academia_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'academia_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Redirigir al dashboard después del login
LOGIN_REDIRECT_URL = 'portada' 

# Redirigir a la página de inicio pública después del logout
LOGOUT_REDIRECT_URL = 'inicio'

# STRIPE
STRIPE_PUBLIC_KEY = 'ProMilitar'

# En settings.py (donde borraste la clave)

try:
    from .local_settings import *
except ImportError:
    # Esto pasará si el archivo no existe (ej. en el servidor si no lo creamos)
    pass

# Configuración de archivos multimedia (Al final del archivo)
MEDIA_URL = '/media/'
import os # <--- Asegúrate de que 'os' está importado arriba, si no, ponlo aquí
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuración de logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'simulador': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# --- CONFIGURACIÓN DE AUTENTICACIÓN (ALLAUTH) ---
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', # Login normal
    'allauth.account.auth_backends.AuthenticationBackend', # Login con Google
]

SITE_ID = 1

# Configuración adicional
LOGIN_REDIRECT_URL = 'portada'   # A dónde van al entrar
LOGOUT_REDIRECT_URL = 'inicio'   # A dónde van al salir
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_LOGIN_ON_GET = True

# --- CREDENCIALES DE GOOGLE (PROVISIONAL) ---
# NOTA: Esto normalmente no se pone directo en el código por seguridad,
# pero para desarrollo local está bien.
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

SITE_ID = 1

# --- CONFIGURACIÓN AVANZADA DE GOOGLE / ALLAUTH ---

# 1. Autenticación
LOGIN_REDIRECT_URL = '/'          # A dónde ir tras loguearse
LOGOUT_REDIRECT_URL = '/'         # A dónde ir tras salir

# 2. Comportamiento del Registro
SOCIALACCOUNT_AUTO_SIGNUP = True  # Registra automáticamente sin pedir datos extra
SOCIALACCOUNT_LOGIN_ON_GET = True # Evita la pantalla intermedia de "¿Quieres entrar?"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False # No pide usuario (lo genera automático)
ACCOUNT_AUTHENTICATION_METHOD = 'email' # Usa el email como identificador principal
ACCOUNT_EMAIL_VERIFICATION = 'none' # No envia correo de confirmación (confiamos en Google)

# 3. Evitar conflictos
SOCIALACCOUNT_ADAPTER = 'allauth.socialaccount.adapter.DefaultSocialAccountAdapter'