"""
Django settings for academia_project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env(DEBUG=(bool, True))
# reading .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default="django-insecure-b8%#e5se7tyx%3$+ws++zbwi)p$4+aq8-e@)21nf*9k^7qk#$r")
GEMINI_API_KEY = env('GEMINI_API_KEY')
OLLAMA_BASE_URL = env('OLLAMA_BASE_URL', default='http://localhost:11434')
OLLAMA_MODEL = env('OLLAMA_MODEL', default='qwen2.5:1.5b')
OLLAMA_KEEPALIVE = env('OLLAMA_KEEPALIVE', default='5m')
OLLAMA_NUM_CTX = env('OLLAMA_NUM_CTX', default=2048)
OLLAMA_TIMEOUT = env('OLLAMA_TIMEOUT', default=30)

# Google OAuth
GOOGLE_CLIENT_ID = env('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = env('GOOGLE_CLIENT_SECRET')

# Redsys Configuration - VALORES FORZADOS PARA SANDBOX
# Override de entorno con valores de prueba estándar
REDSYS_MERCHANT_CODE = '999008881'
REDSYS_TERMINAL = '001'
REDSYS_SECRET_KEY = 'sq7H5Yz6IFZH8Ut440936khq79293474'
REDSYS_CURRENCY = '978'
REDSYS_TRANSACTION_TYPE = '0'
REDSYS_ENVIRONMENT = 'sandbox'
# URLs de retorno para Redsys - configuradas para ngrok
REDSYS_URL_OK = env('REDSYS_URL_OK', default='https://nonostensible-christi-tacky.ngrok-free.dev/pagos/exitoso/')
REDSYS_URL_KO = env('REDSYS_URL_KO', default='https://nonostensible-christi-tacky.ngrok-free.dev/pagos/cancelado/')
REDSYS_WEBHOOK_URL = env('REDSYS_WEBHOOK_URL', default='https://nonostensible-christi-tacky.ngrok-free.dev/api/redsys/webhook/')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = ['*', 'localhost', '127.0.0.1', 'nonostensible-christi-tacky.ngrok-free.dev']


CSRF_TRUSTED_ORIGINS = [
    'https://nonostensible-christi-tacky.ngrok-free.dev',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'simulador',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'academia_project.referral_middleware.ReferralMiddleware',
    'academia_project.course_middleware.CourseAccessMiddleware',
]

ROOT_URLCONF = 'academia_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'academia_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Redirigir al dashboard después del login
LOGIN_REDIRECT_URL = 'portada' 

# Redirigir a la página de inicio pública después del logout
LOGOUT_REDIRECT_URL = 'inicio'

# STRIPE
STRIPE_PUBLIC_KEY = 'ProMilitar'

# En settings.py (donde borraste la clave)

try:
    from .local_settings import *
except ImportError:
    # Esto pasará si el archivo no existe (ej. en el servidor si no lo creamos)
    pass

# Configuración de archivos multimedia (Al final del archivo)
MEDIA_URL = '/media/'
import os # <--- Asegúrate de que 'os' está importado arriba, si no, ponlo aquí
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuración de logging
LOGGING = {
    'version': 1,  
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'simulador': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# --- CONFIGURACIÓN DE AUTENTICACIÓN (ALLAUTH) ---
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# Redirecciones
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Configuración Allauth
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'none'

# Configuración Social
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_LOGIN_ON_GET = True

# Proveedor de Google con credenciales del .env
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
    }
}

# Adaptador personalizado para mantener curso en sesión
SOCIALACCOUNT_ADAPTER = 'academia_project.adapters.SocialAccountAdapter'

# URLs de allauth
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
SOCIALACCOUNT_LOGOUT_REDIRECT_URL = '/'

SILENCED_SYSTEM_CHECKS = ['account.W001']
