# Generated by Django 6.0 on 2026-01-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0004_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='Sube aquí el PDF del tema', null=True, upload_to='temarios/'),
        ),
    ]
