# Generated by Django 6.0 on 2026-01-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0005_tema_archivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='aciertos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='fallos',
            field=models.IntegerField(default=0),
        ),
    ]
