# Generated by Django 6.0 on 2026-01-06 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0006_resultado_aciertos_resultado_fallos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='esta_suscrito',
        ),
        migrations.AddField(
            model_name='perfil',
            name='preguntas_respondidas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rango',
            field=models.CharField(choices=[('Recluta', 'Recluta'), ('Soldado', 'Soldado'), ('Cabo', 'Cabo'), ('Cabo Primero', 'Cabo Primero'), ('Cabo Mayor', 'Cabo Mayor'), ('Sargento', 'Sargento'), ('Sargento Primero', 'Sargento Primero'), ('Brigada', 'Brigada'), ('Subteniente', 'Subteniente'), ('Suboficial Mayor', 'Suboficial Mayor'), ('Teniente', 'Teniente'), ('Capitán', 'Capitán'), ('Comandante', 'Comandante'), ('Teniente Coronel', 'Teniente Coronel'), ('Coronel', 'Coronel'), ('General de Brigada', 'General de Brigada'), ('General de División', 'General de División'), ('Teniente General', 'Teniente General')], default='Recluta', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
