# Generated by Django 6.0 on 2026-01-06 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0008_perfil_esta_suscrito_alter_perfil_rango'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='esta_suscrito',
        ),
        migrations.AlterField(
            model_name='tema',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='temarios/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cursos_activos',
            field=models.ManyToManyField(blank=True, related_name='alumnos', to='simulador.curso'),
        ),
        migrations.AddField(
            model_name='tema',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='simulador.curso'),
        ),
    ]
