# Generated by Django 6.0 on 2026-01-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0009_curso_remove_perfil_esta_suscrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='contenido_texto',
            field=models.TextField(blank=True, help_text='Texto del tema para poder generar audio MP3', null=True),
        ),
    ]
