# Generated by Django 6.0 on 2026-01-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0010_tema_contenido_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='archivo_audio',
            field=models.FileField(blank=True, help_text="Sube aquí el archivo MP3 generado (ej: '01_Reales_Ordenanzas.mp3')", null=True, upload_to='temas_audio/'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='contenido_texto',
            field=models.TextField(blank=True, help_text='Texto del tema (Opcional si ya subes el audio)', null=True),
        ),
    ]
