# Generated by Django 6.0 on 2026-02-25 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0011_tema_archivo_audio_alter_tema_contenido_texto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['materia', 'capitulo', 'bloque', 'numero_tema']},
        ),
        migrations.AddField(
            model_name='pregunta',
            name='explicacion',
            field=models.TextField(blank=True, help_text='Se muestra al fallar o corregir', null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='blancos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tema',
            name='bloque',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tema',
            name='capitulo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tema',
            name='materia',
            field=models.CharField(choices=[('CABO', 'Legislación / Cabo'), ('INGLÉS', 'Inglés'), ('GEOGRAFÍA', 'Geografía'), ('INFORMÁTICA', 'Informática')], default='CABO', help_text='Categoría para agrupar en los acordeones de la web', max_length=20),
        ),
        migrations.AddField(
            model_name='tema',
            name='numero_tema',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='nota',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulador.tema'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='archivo_audio',
            field=models.FileField(blank=True, help_text='Archivo MP3 generado', null=True, upload_to='temas_audio/'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='contenido_texto',
            field=models.TextField(blank=True, help_text='Texto opcional del tema', null=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='nombre',
            field=models.CharField(help_text='Ej: Reales Ordenanzas', max_length=200),
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False)),
                ('preguntas', models.ManyToManyField(to='simulador.pregunta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='resultado',
            name='examen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulador.examen'),
        ),
    ]
