# Generated by Django 6.0 on 2026-03-24 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0012_alter_tema_options_pregunta_explicacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='codigo_referido',
            field=models.CharField(blank=True, help_text='Código único para referral', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='referido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
