# Generated by Django 6.0 on 2026-03-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0013_add_codigo_referido'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='descuento_acumulado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
