# Generated by Django 6.0 on 2026-03-24 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0014_add_descuento_acumulado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(choices=[('ALTA_REFERIDO', 'Alta por referido'), ('RECOMPENSA_RECLUTA', 'Recluta registrado'), ('APLICADO_PAGO', 'Descuento aplicado en pago'), ('SOBRANTE_PAGO', 'Sobrante перенесён')], max_length=30)),
                ('cuantia', models.DecimalField(decimal_places=2, max_digits=6)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_descuentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Descuento',
                'verbose_name_plural': 'Historiales de Descuento',
                'ordering': ['-fecha'],
            },
        ),
    ]
