# Generated by Django 6.0 on 2026-03-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0015_add_historial_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialdescuento',
            name='saldo_resultante',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
