# Generated by Django 6.0 on 2026-03-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0016_add_saldo_resultante'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='es_premium',
            field=models.BooleanField(default=False, help_text='Indica si el usuario tiene suscripción premium activa'),
        ),
    ]
