# Generated by Django 6.0 on 2026-03-24 23:22

import django.db.models.deletion
import simulador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0017_add_es_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoContexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del documento', max_length=200)),
                ('tipo', models.CharField(choices=[('TEMARIO', 'Temario'), ('CONVOCATORIA', 'Convocatoria'), ('NORMATIVA', 'Normativa')], default='TEMARIO', max_length=20)),
                ('archivo', models.FileField(blank=True, help_text='PDF del temario o convocatoria', null=True, upload_to=simulador.models.documento_upload_path)),
                ('contenido_texto', models.TextField(blank=True, help_text='Texto extraído automáticamente del PDF', null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(help_text='Curso al que pertenece este documento', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='simulador.curso')),
            ],
            options={
                'verbose_name': 'Documento de Contexto',
                'verbose_name_plural': 'Documentos de Contexto',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
